[ 2024-09-17 02:52:19,448 ] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.225.126:5000
[ 2024-09-17 02:52:19,448 ] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2024-09-17 02:53:36,583 ] 97 werkzeug - INFO - 127.0.0.1 - - [17/Sep/2024 02:53:36] "GET / HTTP/1.1" 200 -
[ 2024-09-17 02:53:36,800 ] 97 werkzeug - INFO - 127.0.0.1 - - [17/Sep/2024 02:53:36] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2024-09-17 02:53:46,742 ] 97 werkzeug - INFO - 127.0.0.1 - - [17/Sep/2024 02:53:46] "GET /predictdata HTTP/1.1" 200 -
[ 2024-09-17 02:54:33,055 ] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\src\pipeline\predict_pipeline.py", line 13, in predict
    model_path=os.path.join("artifacts","model.pkl")
               ^^
NameError: name 'os' is not defined. Did you forget to import 'os'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\app.py", line 40, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [C:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\src\pipeline\predict_pipeline.py] line number [13] error message[name 'os' is not defined]
[ 2024-09-17 02:54:33,056 ] 97 werkzeug - INFO - 127.0.0.1 - - [17/Sep/2024 02:54:33] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[ 2024-09-17 02:55:20,341 ] 97 werkzeug - INFO - 127.0.0.1 - - [17/Sep/2024 02:55:20] "GET /predictdata HTTP/1.1" 200 -
[ 2024-09-17 02:55:37,775 ] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\src\pipeline\predict_pipeline.py", line 13, in predict
    model_path=os.path.join("artifacts","model.pkl")
               ^^
NameError: name 'os' is not defined. Did you forget to import 'os'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\app.py", line 40, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [C:\Users\ashis\Work\Project\Hawk\Code\Edureka\mlproject\src\pipeline\predict_pipeline.py] line number [13] error message[name 'os' is not defined]
[ 2024-09-17 02:55:37,780 ] 97 werkzeug - INFO - 127.0.0.1 - - [17/Sep/2024 02:55:37] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
